"""Inicial

Revision ID: 9918fabf987b
Revises: 
Create Date: 2025-09-18 22:15:56.877402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9918fabf987b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pedido_historial')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('clientes')
    op.drop_table('whatsapp_logs')
    op.drop_table('pagos')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('clave'))

    op.drop_table('app_settings')
    op.drop_table('pedido_items')
    op.drop_table('sync_queue')
    op.drop_table('producto_imagenes')
    op.drop_table('movimientos_inventario')
    op.drop_table('mesas')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('orden')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('codigo'))
        batch_op.drop_index(batch_op.f('idx_pedidos_created_at'))
        batch_op.drop_index(batch_op.f('idx_pedidos_estado'))
        batch_op.drop_constraint(batch_op.f('pedidos_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pedidos_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pedidos_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('estado')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('codigo')
        batch_op.drop_column('creado_por')
        batch_op.drop_column('mesa_id')
        batch_op.drop_column('total')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_productos_categoria'))
        batch_op.drop_index(batch_op.f('sku'))
        batch_op.drop_constraint(batch_op.f('productos_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('productos_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('sku')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('name'))
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_usuarios_role'))
        batch_op.drop_constraint(batch_op.f('usuarios_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('telefono')
        batch_op.drop_column('activo')
        batch_op.drop_column('role_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('role_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuarios_ibfk_1'), 'roles', ['role_id'], ['id'], onupdate='CASCADE')
        batch_op.create_index(batch_op.f('idx_usuarios_role'), ['role_id'], unique=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('rol_id')
        batch_op.drop_column('password')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('nombre')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('sku', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('productos_ibfk_1'), 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('productos_ibfk_2'), 'usuarios', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('idx_productos_categoria'), ['categoria_id'], unique=False)
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('total', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False))
        batch_op.add_column(sa.Column('mesa_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creado_por', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('estado', mysql.ENUM('nuevo', 'confirmado', 'en_preparacion', 'listo', 'enviado', 'entregado', 'cancelado'), server_default=sa.text("'nuevo'"), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedidos_ibfk_3'), 'usuarios', ['creado_por'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('pedidos_ibfk_2'), 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('pedidos_ibfk_1'), 'mesas', ['mesa_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_pedidos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('idx_pedidos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('codigo'), ['codigo'], unique=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('orden', mysql.SMALLINT(display_width=6), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)

    op.create_table('mesas',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('capacidad', mysql.SMALLINT(display_width=6), server_default=sa.text("'4'"), autoincrement=False, nullable=True),
    sa.Column('ubicacion', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('estado', mysql.ENUM('libre', 'ocupada', 'reservada'), server_default=sa.text("'libre'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('entrada', 'salida', 'ajuste'), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('razon', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('movimientos_inventario_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('movimientos_inventario_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_imagenes',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('orden', mysql.SMALLINT(display_width=6), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('producto_imagenes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sync_queue',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('source_device_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('action_type', mysql.ENUM('create', 'update', 'delete'), nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'en_proceso', 'sync_ok', 'fallo'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('intentos', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('last_error', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pedido_items',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pedido_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('nombre_producto', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('notas', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('pedido_items_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('pedido_items_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('app_settings',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('clave', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('valor', mysql.TEXT(), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('clave'), ['clave'], unique=True)

    op.create_table('pagos',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pedido_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', mysql.ENUM('efectivo', 'tarjeta', 'transferencia', 'otro'), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'completado', 'fallido'), server_default=sa.text("'completado'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('pagos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('whatsapp_logs',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pedido_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('destinatario', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mensaje', mysql.TEXT(), nullable=False),
    sa.Column('proveedor', mysql.ENUM('twilio', 'wa-business-api', 'otro'), server_default=sa.text("'twilio'"), nullable=True),
    sa.Column('status', mysql.ENUM('pendiente', 'enviado', 'fallo'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('respuesta_proveedor', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('whatsapp_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('pedido_historial',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pedido_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('estado_anterior', mysql.ENUM('nuevo', 'confirmado', 'en_preparacion', 'listo', 'enviado', 'entregado', 'cancelado'), nullable=True),
    sa.Column('estado_nuevo', mysql.ENUM('nuevo', 'confirmado', 'en_preparacion', 'listo', 'enviado', 'entregado', 'cancelado'), nullable=True),
    sa.Column('cambiado_por', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('nota', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cambiado_por'], ['usuarios.id'], name=op.f('pedido_historial_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('pedido_historial_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('detalles_pedido')
    # ### end Alembic commands ###
